### ISSUE TITLE
Venv `__pycache__` directories filling up

### ISSUE THREAD

**Issue by Thomas-Christie** [google/jaxtyping#102]
Hi,

Thanks for the excellent library.  I'm currently working on a project which uses Jaxtyping +Beartype. I'm able to run our unit tests using Jaxtyping + Beartype via the [recommended method](https://github.com/google/jaxtyping/blob/main/jaxtyping/_import_hook.py#L343C5-L354) using the `pyproject.toml` file. 

However, I have noticed that the `__pycache__` directories within my `venv` are filling up. For instance, each time I run tests and look inside `venv/lib/python3.10/site-packages/tensorflow_probability/__pycache__`, I get a new `__init__.*.pyc` (e.g. `e.g. __init__.cpython-310.opt-jaxtyping63529791564383655159.pyc`).  I don’t think these `*.pyc` files should be generated every time, as the corresponding `__init__` isn’t changing between runs, and if I don't run with Jaxtype + Beartype then these `*.pyc` files aren't generated. 

I'm wondering if this is a bug or there is a way for me to prevent this from happening? It is currently a bit of an issue as it causes my `venv` to become pretty bloated, particularly if working in VSCode with autosave enabled and the `python.testing.autoTestDiscoverOnSaveEnabled` flag set to true, as these `*.pyc` files are getting generated very frequently as I edit tests.

Thanks!

**Comment by patrick-kidger** [comment]
Thanks for the report! This is indeed a bug. It should be fixed in #103, and I'll do a new release with this.
