### ISSUE TITLE
test_import_hook_transitive is flaky!

### ISSUE THREAD

**Issue by knyazer** [google/jaxtyping#121]
Hi Patrick!

I noticed that on the main branch I experience some flakiness of the transitive import hook test: sometimes it fails, sometimes it succeeds, without changes in the source code. I think it might be due to the recent commit with the update of the import hook test suite, probably something is asynchronous in the pytest, which leads to not being able to generate/discover the newly written file consistently.

Approximately 1 in 5 runs of ```pytest test/test_import_hook.py``` the ```test_import_hook_transitive``` fails with an error message ```ModuleNotFoundError: No module named 'jaxtyping_transitive_test'```.

To be precise, the issue exists on the latest commit https://github.com/google/jaxtyping/commit/17092ad8d85df7f76a704404a45a3bcaf7a6b5b7, but it not present on the previous one, https://github.com/google/jaxtyping/commit/75392d63309e2caf2ecb5bc95643fa78e324eb8d .

**Comment by patrick-kidger** [comment]
Hmm. I've just checked and I don't think this is something in pytest, as the relevant code is entirely inside the test.

Maybe some aynchronicity at the OS level, to do with writing files? In which case maybe this is OS-dependent or something.

Inelegant as it is, I'm tempted to just add a 1-second sleep.

**Comment by knyazer** [comment]
Fixed by #122
