### ISSUE TITLE
Order of symbolic expression evaluation

### ISSUE THREAD

**Issue by alexoshin** [google/jaxtyping#126]
I am encountering an error when using symbolic expressions for annotating argument shapes. It seems like the error is due to the arguments being evaluated symbolically in order from first to last. This is a MWE:
```python
import jax.numpy as jnp
from jaxtyping import Float, Array, jaxtyped
from beartype import beartype as typechecked

@jaxtyped
@typechecked
def ideal_fn(a: Float[Array, "T+1"], b: Float[Array, "T"]) -> Float[Array, ""]:
    return jnp.sum(a**2) + jnp.sum(b**2)

a = jnp.ones(3)
b = jnp.ones(2)
ideal_fn(a, b)
>>> NameError: Cannot process symbolic dimension ...
```

```T``` here represents the number of timesteps and has meaning both to the developer as well as end-user. Redefining the symbolic dimension is a fine workaround:
```python
@jaxtyped
@typechecked
def not_as_clear_fn(a: Float[Array, "Tp1"], b: Float[Array, "Tp1-1"]) -> Float[Array, ""]:
    return jnp.sum(a**2) + jnp.sum(b**2)
not_as_clear_fn(a, b)
>>> Array(5., dtype=float32)
```
Unfortunately, this is way less intuitive if I want to reuse the type of ```b``` in other functions. This is what I'm currently using, but I was wondering if there was a smarter way of handling this.

Reversing the arg order works, but this is not ideal for clarity reasons, and also would require me to refactor every method that calls this function:
```python
@jaxtyped
@typechecked
def reverse_args_fn(b: Float[Array, "T"], a: Float[Array, "T+1"]) -> Float[Array, ""]:
    return jnp.sum(a**2) + jnp.sum(b**2)
reverse_args_fn(b, a)
>>> Array(5., dtype=float32)
```

Of course, manually checking the shape works, but I feel this defeats the purpose of using jaxtyping in the first place:
```python
@jaxtyped
@typechecked
def no_check_fn(a: Float[Array, "Tp1"], b: Float[Array, "T"]) -> Float[Array, ""]:
    assert a.shape[0] == b.shape[0] + 1
    return jnp.sum(a**2) + jnp.sum(b**2)
no_check_fn(a, b)
>>> Array(5., dtype=float32)
```

One proposed fix would work as follows:
```python
from functools import partial
@partial(jaxtyped, sym_eval_order=(1, 0))
@typechecked
def improved_fn(a: Float[Array, "T+1"], b: Float[Array, "T"]) -> Float[Array, ""]:
    return jnp.sum(a**2) + jnp.sum(b**2)
```
This would ensure the shape of ```b``` is evaluated before ```a```. Alternatively, would it be possible to evaluate dimensions without any expressions first, and then evaluating the other arguments? Let me know what you think. Thanks!

**Comment by patrick-kidger** [comment]
The order in which argments are checked is a property of your typechecker, in this case `beartype.beartype`. It's not a property of `jaxtyping`.

I'd suggest opening this as a feature request over there! There's not a lot more that jaxtyping can do unfortunately.

**Comment by alexoshin** [comment]
Thanks for the quick response! I'll take a look over there.
