### ISSUE TITLE
Operator support

### ISSUE THREAD

**Issue by wookayin** [google/jaxtyping#14]
This is not a comprehensive list, but many of the arithmetic operator doesn't seem fully supported yet.

Example:

> Pyright: Operator "-" not supported for types "f" and "f"

```python
import jax.numpy as jnp
import jaxtyping

a: jaxtyping.f = jnp.zeros(3)
b: jaxtyping.f = jnp.ones(3)

c = a - b  # Pyright: Operator "-" not supported for types "f" and "f"
print(c)  # prints [-1 -1 -1], a valid code
```

pyright 1.1.269 (latest, 2022-09-03)

**Comment by wookayin** [comment]
Might be related to https://github.com/google/jaxtyping/blob/main/FAQ.md#what-about-support-for-static-type-checkers-like-mypy-pyright-etc

I don't expect the static type check working correctly, but the diagnostics error messages are quite annoying.

**Comment by patrick-kidger** [comment]
Yep, this is because of the lack of support for static typing.

The good news is that support for this is just around the corner: #13.

**Comment by wookayin** [comment]
Congratulations on v0.2.0 and rewriting (#16)!  I like the new APIs.

With the new APIs, it is now more compatible with static type checkers (pyright, mypy no longer complains the false-positive errors):

```
a: jaxtyping.Float = jnp.zeros(3)   # or jaxtyping.Float[jaxtyping.Array]
b: jaxtyping.Float = jnp.ones(3)

c = a - b  # pyright thinks it's okay
print(c)
```
