### ISSUE TITLE
Old-style decoration fails to raise on dataclasses since 0.2.24

### ISSUE THREAD

**Issue by EtaoinWu** [google/jaxtyping#149]
With the following code:

```python
from beartype import beartype
from dataclasses import dataclass
from jaxtyping import *
from jax import numpy as jnp

# old-style decoration
@jaxtyped
@beartype
@dataclass
class X:
  u: Num[Array, "a"]
  v: Num[Array, "a a"]

X(jnp.empty(4), jnp.empty((3, 4))) # raises as expected
X(jnp.empty(4), jnp.empty((3, 3))) # fails to raise since v0.2.24
```

The last line fails to raise, since [the current decorator on dataclasses](https://github.com/google/jaxtyping/blob/8e47c9081c3eae5ce6b3b5e3141d0cf81c27522e/jaxtyping/_decorator.py#L187) only works when a `typechecker` is passed.

Is this intentional?

**Comment by patrick-kidger** [comment]
Yup, that is intentional -- old-style decoration never supported this. (And it's not clear if it could be made to do so either.)
