### ISSUE TITLE
Is the version requirement too strict?

### ISSUE THREAD

**Issue by alok** [google/jaxtyping#15]
https://github.com/google/jaxtyping/blob/3f9fad59bdb180f3d70ae3fd864d37ea85adcdc6/setup.py#L66

Does this have to be ~3.7?

**Comment by patrick-kidger** [comment]
So it's not been tested with any lower version. (Realistically folks should really be upgrading their versions of Python if they're on anything older!)

You're welcome to try installing it on a lower version, but there are no promises it'll work.

**Comment by ayaka14732** [comment]
It's not too strict. My new projects are using Python "~=3.8", and I am planning to use "~=3.9" for `list[str]` instead of `List[str]`, and even further "~=3.10" for the better error messages.

**Comment by alok** [comment]
I mean strict in the sense that only 3.7 works. I am a maximalist and would personally make the required version 3.10

**Comment by ayaka14732** [comment]
`"~= 3.7"` means `">= 3.7, == 3.*"`
