### ISSUE TITLE
jax.tree_leaves should be replaced by jax.tree_util.tree_leaves

### ISSUE THREAD

**Issue by murphyk** [google/jaxtyping#39]
https://github.com/google/jaxtyping/blob/main/jaxtyping/pytree_type.py#L86
```
leaves = jax.tree_leaves(obj, is_leaf=is_leaftype)
```

I am using jax '0.3.23'

**Comment by patrick-kidger** [comment]
Thanks for the nudge; I'd been meaning to do this. Fixed in #40.
(I'll hold off on doing another release for now in case there's anything else worth including in the near future.)
