### ISSUE TITLE
pip installing jaxtyping prints an error in colab

### ISSUE THREAD

**Issue by slinderman** [google/jaxtyping#42]
`%pip install jaxtyping` throws an error in Colab. The installation still succeeds, but it prints this scary block of red text:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.1.5 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < "3.8", but you have typing-extensions 4.4.0 which is incompatible.
spacy 3.4.2 requires typing-extensions<4.2.0,>=3.7.4; python_version < "3.8", but you have typing-extensions 4.4.0 which is incompatible.
confection 0.0.3 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < "3.8", but you have typing-extensions 4.4.0 which is incompatible.
```

We use `jaxtyping` as a dependency for [dynamax](https://github.com/probml/dynamax), so pip installing our package produces this error message as well. tagging @murphyk as well.

**Comment by patrick-kidger** [comment]
I don't think this is an issue with jaxtyping. Rather, the issue is that the packages listed (in the error message) have a maximum compatible version of `typing_extensions`.

I don't think those packages have anything to do with jaxtyping, and are just other things that you happen to have installed. I'd suggest reaching out to their authors.

**Comment by slinderman** [comment]
I think the problem is that `jaxtyping` requires `typing_extensions >= 4.2.0` (see [here](https://github.com/google/jaxtyping/blob/main/setup.py#L74) whereas `thinc`, `spacy`, and `confection`, which are all installed on Colab images by default, requires `typing_extensions < 4.2` (see [here](https://github.com/explosion/confection/blob/main/setup.cfg#L33)). 

Does jaxtyping really need `typing_extensions >= 4.2.0`?

**Comment by patrick-kidger** [comment]
I think `4.2.0` was just the most recent version when I first released jaxtyping. Probably a lower version would suffice. I'd be happy to accept a PR on this if you can verify that jaxtyping works okay with a lower version.

**Comment by slinderman** [comment]
Sorry to let this slide. I ended working around it by just capturing the output of the pip install cell. Would be nice to relax the version constraints but no big deal.

**Comment by patrick-kidger** [comment]
I think this should be fixed. Jaxtyping now has a more relaxed version constraint.
