### ISSUE TITLE
Vanilla dataclasses don't work

### ISSUE THREAD

**Issue by brentyi** [google/jaxtyping#55]
Hi!

This condition:
https://github.com/google/jaxtyping/blob/59e8fb0d18325f990a9d59ee35e90c04b699cab8/jaxtyping/decorator.py#L71

Returns `True` for equinox modules, but `False` for vanilla dataclasses. Here's a reproduction: https://github.com/brentyi/jaxtyping-export-repro/tree/broken_dataclasses

Perhaps the decorator here should be prepended rather than appended? Otherwise, `_jaxtyped_typechecker` will be called before `@dataclass`.
https://github.com/google/jaxtyping/blob/59e8fb0d18325f990a9d59ee35e90c04b699cab8/jaxtyping/import_hook.py#L114

( if this seems like a valid/trivial fix I'm happy to make a PR, maybe this weekend )

**Comment by patrick-kidger** [comment]
Agreed, this should be switched from `append(...)` to `insert(0, ...)`. Happy to take a PR on this.
