### ISSUE TITLE
[Question] Partial shape initialization

### ISSUE THREAD

**Issue by younik** [google/jaxtyping#60]
I am a newbie with `jaxtyping`; I am wondering if it is possible to have partial initialization of shapes or nested definitions.

In my case, I have a shape for a sample of data that I would like to define once:
```python
MyDataType = Float[Array, "chan1 chan2 chan3 features"]
```

And then, I would like to reuse `MyDataType` definition multiple times to define batches of different lengths.
I tried something like:
```python
Batch = Float[MyDataType, "batch_size"]
```
but it doesn't see `batch_size` as a new axis.

An alternative useful feature for doing this would be a partial initialization like:
```python
Batch = Float[Array, "$1 chan1 chan2 chan3 features"]

Batch["n"] == Float[Array, "n chan1 chan2 chan3 features"]
```

A workaround like this works:
```python
class _MetaBatch(type):
    def __getitem__(cls, s: str):
        return Float[Array, f"{s} chan1 chan2 chan3 features"]

class Batch(metaclass=_MetaBatch):
  pass
```

Is there a more elegant way of doing this?

**Comment by patrick-kidger** [comment]
How about:
```python
my_data_shape = "chan1 chan2 chan3 features"
MyDataType = Float[Array, my_data_shape]
Batch = Float[Array, "batch " + my_data_shape]
```
?

**Comment by younik** [comment]
The problem is that often I need to define two batches with different sizes, e.g.

```python
sample(dataset: Float[Array, "size " + my_data_shape], length: int) -> Float[Array, "length " + my_data_shape]:
```

this work of course, but the notation is still a bit overloaded

**Comment by patrick-kidger** [comment]
Hmm. Right now I don't think this is a common use-case. As such I'm inclined to suggest that the best way to handle this is  by using a user-land wrapper, as you currently are.

That said, if anyone else is reading this and thinks this would be a useful feature, please do speak up! If there's enough interest then it may be worth adding the extra complexity (of managing another feature) to jaxtyping.

**Comment by younik** [comment]
> Hmm. Right now I don't think this is a common use-case. As such I'm inclined to suggest that the best way to handle this is by using a user-land wrapper, as you currently are.
> 
> That said, if anyone else is reading this and thinks this would be a useful feature, please do speak up! If there's enough interest then it may be worth adding the extra complexity (of managing another feature) to jaxtyping.

Perfect, thank you!
