### ISSUE TITLE
[Question] Is there a way to annotate equal shape for input and return?

### ISSUE THREAD

**Issue by eigenvivek** [google/jaxtyping#63]
Thank you for this library.

I have a function that accepts a tensor and should return a tensor of equal shape. The input shape can be anything, but the output shape should always be the same. Is there a good way to annotate this with the library?

I read the [shape API](https://github.com/google/jaxtyping/blob/main/API.md#shape) and settled on this:
```Python
def f(x: Float[torch.Tensor, "*"]) -> Float[torch.Tensor, "*"]:
    ....
```
but I believe this would allow `f` to return a tensor of any shape, not necessarily one that matches `x`.

**Comment by patrick-kidger** [comment]
What you have written should be exactly what you're after, i.e. it should require that `f` returns a tensor of the same shape as its input. Is this not the behaviour you observe in practice?

**Comment by eigenvivek** [comment]
It doesn't seem to require that `f`'s output be the same shape the input, for example

```python
import torch
from jaxtyping import Float


def f(x: Float[torch.Tensor, "*"]) -> Float[torch.Tensor, "*"]:
    return torch.stack([x, x])


x = torch.rand(5, 1, 100, 100)
print(f(x).shape)
```

returns `torch.Size([2, 5, 1, 100, 100])` with no exception.

**Comment by patrick-kidger** [comment]
You need to use a typechecking library alongside jaxtyping; typically either beartype or typeguard.

jaxtyping just provides the types, so your example is passing just like how `def f(x: int): ...; f("some string")` will also pass.

Check out the jaxtyping documentation on using a runtime typechecker.

**Comment by eigenvivek** [comment]
Ahhh I see, I didn't know about `@jaxtyped`. Thanks Patrick!
