### ISSUE TITLE
Single / multiple dispatch with jaxtyping types

### ISSUE THREAD

**Issue by mthiboust** [google/jaxtyping#67]
Is there a way to use jaxtyping types with `functools.singledispatch` or the `multipledispatch` library? I tried with the following code with no success:

```python
import functools as ft
import jax.numpy as jnp
from jaxtyping import Array, Shaped, jaxtyped

@jaxtyped
@ft.singledispatch
def f(image):
    raise NotImplementedError(f"{type(image)} not impemented")

@jaxtyped
@f.register
def _(image: Shaped[Array, "h w 4"]):
    # process a RGBA image
    pass

@jaxtyped
@f.register
def _(image: Shaped[Array, "h w 3"]):
    # process a RGB image
    pass

@jaxtyped
@f.register
def _(image: Shaped[Array, "h w"]):
    # process a grayscale image
    pass

f(jnp.ones((100, 100, 3)))  # NotImplementedError: <class 'jaxlib.xla_extension.Array'> not impemented
```

**Comment by patrick-kidger** [comment]
I've not tried using `multipledispatch` (or [plum]((https://github.com/wesselb/plum), which I think is generally a bit better than `multipledispatch`) with jaxtyping. I'm not sure what it would take to make that work, but it might be possible. (If any changes are needed to jaxtyping then I'd be happy to accept a PR on this.)

I'm afraid it almost certainly won't be possible using `singledispatch` though, I'm afraid. This works by checking the `__class__` attribute of the first argument ([implementation here](https://github.com/python/cpython/blob/eb5565918ab9f814fc3490f0604ee0c96cd981b4/Lib/functools.py#L909)), and in particular this doesn't carry any shape/dtype information.

**Comment by mthiboust** [comment]
Thanks Patrick for your answer. I tried using `plum` as you suggested. It does not work with `plum v1` but it seems that their forthcoming `plum v2` may be able to support the jaxtyping types because it will entirely relies on `isinstance` checks to perform the dispatch. You can see their example to dispatch on NumPy array shapes and sizes [here](https://github.com/wesselb/plum/pull/73). 

I'll have a closer look at this when their v2 will be ready.

**Comment by patrick-kidger** [comment]
jaxtyping should now be compatible with the upcoming Plum v2! (See also the discussion in https://github.com/wesselb/plum/pull/73.)

**Comment by mthiboust** [comment]
Great to hear, thanks @patrick-kidger
