### ISSUE TITLE
Add `dtype` type

### ISSUE THREAD

**Issue by joeryjoery** [google/jaxtyping#74]
Hi, I wanted to ask if there could be a type annotation/ alias for specifying compatible type arguments.

Maybe this already exists, but I'm not yet aware of it.

For example:
```python
import typing
import jaxtyping

import jax


# Right now: `dtype = ??` or jax._src.typing defines `dtype = Union[str, np.dtype, Any, SupportsDType]`.
def myfun(shape: int | typing.Sequence[int], dtype: ...) -> jaxtyping.Num[jaxtyping.Array, '...']:
    return jnp.zeros(shape, dtype)


# Desired
def myfun(shape: int | typing.Sequence[int], dtype: jaxtyping.JaxDTypeLike) -> jaxtyping.Num[jaxtyping.Array, '...']:
    return jnp.zeros(shape, dtype)

# Maybe interesting?
@typing.overload
def myfun(shape: int | typing.Sequence[int], dtype: jaxtyping.JaxIntTypeLike) -> jaxtyping.Integer[jaxtyping.Array, '...']:
    ...

@typing.overload
def myfun(shape: int | typing.Sequence[int], dtype: jaxtyping.JaxFloatTypeLike) -> jaxtyping.Float[jaxtyping.Array, '...']:
    ...
```
I saw that `jax.typing.DTypeLike` exists, but it is still private...

This would e.g., be useful for annotating neural network parameter initializers, which often depend on an explicit dtype.

**Comment by patrick-kidger** [comment]
Yup, this is on the roadmap to add. The plan here is to make this available through jaxtyping as they become available through `jax.typing`.

For now I'd probably just recommend using `Any` (which is part of the `Union` that `jax.typing` has anyway).

**Comment by joeryjoery** [comment]
Hey, that's great. Guess I'll have to be a bit patient ;).
