### ISSUE TITLE
str: int option?

### ISSUE THREAD

**Issue by callummcdougall** [google/jaxtyping#76]
Hi,

`torchtyping` has the option for a `str: int` pair, e.g.:

```python
x: TT["cols": 3, "rows": 4]
```

which was helpful if you wanted to both (1) name the dimensions and (2) fix them to specific values. Does `jaxtyping` have a similar feature? If it does, I can't find it currently. (e.g. it seems like `Float[t.Tensor, "cols=3 rows=4"]` (or `:` rather than `=`) would be quite natural here, but that doesn't seem to be allowed).

Thanks for the awesome library! (-:

**Comment by patrick-kidger** [comment]
Seems reasonable to me! I've just added this and done a new release (v0.2.15).

**Comment by callummcdougall** [comment]
Thanks, yeah this looks awesome!
