### ISSUE TITLE
Unclear errors from beartype/typeguard (possibly misused!)

### ISSUE THREAD

**Issue by phinate** [google/jaxtyping#79]
Hi Patrick! Using `jaxtyping` for the first time, and ran into some peculiar error messages for a basic RNN example when using `beartype`/`typeguard`.  

I'll paste the code first, and then the errors:

```python3
import jax
import jax.numpy as jnp
from jaxtyping import Array, Float, jaxtyped
from beartype import beartype as typechecker  
# from typeguard import typechecked as typechecker  # uncomment to get typeguard error
from equinox import Module as JaxClass


@jaxtyped
@typechecker
class Parameters(JaxClass):
    embedding_weights: Float[Array, "hidden_state embedding"]
    hidden_state_weights: Float[Array, "hidden_state hidden_state"]
    output_weights: Float[Array, "embedding hidden_state"]
    hidden_state_bias: Float[Array, "hidden_state"]
    output_bias: Float[Array, "embedding"]

e = 12
h = 10

init_pars = Parameters(jnp.ones((h,e)), jnp.ones((h,h)), jnp.ones((e,h)), jnp.ones((h,)), jnp.ones((e,)))
init_state = jnp.ones((h,))
random_embed = jnp.zeros((e,)).at[3].set(1)

@jax.jit
@jaxtyped
@typechecker
def update_hidden_state(
    embedding: Float[Array, "embedding"], 
    hidden_state: Float[Array, "hidden_state"], 
    params: Parameters
) -> Float[Array, "embedding"]:
    return params.hidden_state_weights @ hidden_state + params.embedding_weights @ embedding + params.hidden_state_bias

update_hidden_state(random_embed, init_state, init_pars)
```

First, `beartype`: the runtime checking behaves as expected when the shapes match. If, however, I return an array of shape `"embedding"` in `update_hidden_state`, I correctly get a complaint, but it's a bit obscure:

```
BeartypeCallHintReturnViolation: Function __main__.update_hidden_state() return "Tracedwith" violates type hint , as  "Tracedwith" not instance of .
```

which makes it seem like some function name is not being propagated or something (also fairly new to runtime type checking, but I would assume the error should be a little clearer!)

If I uncomment the `typeguard` line, it's even less clear what I'm doing wrong:

```
TypeError:  is a built-in module
```

which again, seems to be missing the name of something? Hoping this is just me not using something correctly :p 

This was replicable on python 3.8 and 3.11 virtual envs.

Versions:
typeguard==3.0.2
jax==0.4.8
jaxlib==0.4.7
jaxtyping==0.2.15
equinox==0.10.3
beartype==0.14.0

**Comment by patrick-kidger** [comment]
For beartype, this is the error message I get:
```
beartype.roar.BeartypeCallHintReturnViolation: Function __main__.update_hidden_state() return "Traced<ShapedArray(float32[10])>with<DynamicJaxprTrace(level=1/0)>" violates type hint <class 'jaxtyping.Float[Array, 'embedding']'>, as <protocol "jax._src.interpreters.partial_eval.DynamicJaxprTracer"> "Traced<ShapedArray(float32[10])>with<DynamicJaxprTrace(level=1/0)>" not instance of <class "jaxtyping.Float[Array, 'embedding']">.
```
I do note that it is producing coloured output in my terminal. Perhaps your terminal doesn't support colour, and this produces your odd-looking error message? I'd suggest opening a beartype issue if so; ideally beartype should disable its use of colour in this scenario.

I can't reproduce your typeguard error. I get error:
```
typeguard.TypeCheckError: the return value (jax._src.interpreters.partial_eval.DynamicJaxprTracer) is not an instance of jaxtyping.Float[Array, 'embedding']
```
which looks like the expected error message.
(I'll grant you that it doesn't really tell you that it's due to a shape error in particular -- this is a known issue (#6) and something that at least beartype has plans to fix (https://github.com/beartype/beartype/issues/235))

This is in a fresh conda environment with the same versions of the packages as you list.

**Comment by phinate** [comment]
Thanks for double checking! It turned out that the main difference was me operating within a VSCode notebook environment (definitely should have mentioned) -- perhaps Jupyter is not the intended usage of the runtime type checkers? I'll search around and see if theres a good place to report this behaviour in the respective libs.

Will close, thanks again!
