### ISSUE TITLE
Class 'Array' does not define '__add__', so the '+' operator cannot be used on its instances 

### ISSUE THREAD

**Issue by jacob-jacob-jacob** [google/jaxtyping#88]
I get the above Warning in Pycharm. I also get other warnings about `.shape` not being defined. Is there any way to make the warning work better, or another IDE that understands the `Array` type of this package? `mypy` works.

**Comment by patrick-kidger** [comment]
Can you provide a MWE? And, are you on the latest JAX version? I don't get the same issue.

FWIW `Array` defines the `__add__` method [here](https://github.com/google/jax/blob/a7b8129ffbcd73af26cd075bb8f248be5f64b906/jax/_src/basearray.pyi#L76), and this works alright with e.g. pyright-lsp.

**Comment by jacob-jacob-jacob** [comment]
Hello, thank you for the prompt answer. I was using a `0.3.x` version of jax and also an older version of jaxtyping. But this finally gave me a reason to update and now everything works. Thanks!
