### ISSUE TITLE
[Question] Torch variable type-hints & beartype.door.die_if_unbearable()

### ISSUE THREAD

**Issue by MaximilienLC** [google/jaxtyping#97]
Hi!

Thanks for the great package. I was wondering whether you knew if performing run-type checking for variable assignments (of this sort https://github.com/google/jaxtyping/issues/7) in the ``forward()`` method with ``beartype.door.die_if_unbearable()`` (implicitely with beartype >=0.5.0) would degrade performance when training on GPU, maybe having to bring the tensors back onto the CPU to obtain their shape informations?

Thanks!

**Comment by patrick-kidger** [comment]
I don't think it should. I believe PyTorch makes shape/dtype information available on the CPU regardless of where the buffer-of-numbers itself is stored.
